import '../models/deal.dart';
import '../models/coupon.dart';

/// Uygulama başladığında gösterilecek gerçekçi demo veriler.
/// API veya scraper veri getirdiğinde bunların yerini alır.
class MockDataService {
  static List<Deal> getDailyDeals() {
    return [
      // ═══════════ YEMEK FıRSATLARı ═══════════
      Deal(
        id: 'ys_1',
        title: 'Burger King Whopper Menü',
        description: 'Whopper + Patates + İçecek. Yemeksepeti özel indirim!',
        imageUrl: 'https://cdn.getiryemek.com/restaurants/1605683826447_1125x522.jpeg',
        platform: 'Yemeksepeti',
        category: 'food',
        originalPrice: 219.90,
        discountedPrice: 149.90,
        discountPercent: 32,
        couponCode: 'BURGER30',
        url: 'https://www.yemeksepeti.com',
        expiryDate: DateTime.now().add(const Duration(hours: 12)),
        isFlashDeal: true,
        isHot: true,
        createdAt: DateTime.now(),
      ),
      Deal(
        id: 'ys_2',
        title: 'Dominos Orta Boy Pizza',
        description: '2. pizza 1 TL kampanyası devam ediyor!',
        imageUrl: 'https://cdn.yemeksepeti.com/app_images/img-dominos.jpg',
        platform: 'Yemeksepeti',
        category: 'food',
        originalPrice: 259.90,
        discountedPrice: 179.90,
        discountPercent: 31,
        couponCode: 'PIZZA40',
        url: 'https://www.yemeksepeti.com',
        expiryDate: DateTime.now().add(const Duration(days: 1)),
        isHot: true,
        createdAt: DateTime.now(),
      ),
      Deal(
        id: 'getir_1',
        title: 'Getir Yemek - İlk Sipariş',
        description: 'İlk siparişe özel %25 indirim kodu!',
        imageUrl: 'https://cdn.getir.com/marketing/Getir_water_1620x1080_l2zyg1.jpg',
        platform: 'Getir',
        category: 'food',
        originalPrice: 200.00,
        discountedPrice: 150.00,
        discountPercent: 25,
        couponCode: 'MERHABA25',
        url: 'https://getir.com',
        expiryDate: DateTime.now().add(const Duration(days: 7)),
        isFlashDeal: true,
        createdAt: DateTime.now(),
      ),

      // ═══════════ ELEKTRONİK ═══════════
      Deal(
        id: 'ty_1',
        title: 'Samsung Galaxy Buds FE',
        description: 'ANC özellikli kablosuz kulaklık. En düşük fiyat!',
        imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/61Qqg+T8nsL._AC_SL1500_.jpg',
        platform: 'Trendyol',
        category: 'electronics',
        originalPrice: 2499.00,
        discountedPrice: 1699.00,
        discountPercent: 32,
        url: 'https://www.trendyol.com',
        expiryDate: DateTime.now().add(const Duration(days: 5)),
        isHot: true,
        createdAt: DateTime.now(),
      ),
      Deal(
        id: 'amz_1',
        title: 'Philips Airfryer XXL',
        description: 'Premium airfryer, en düşük fiyat garantisi!',
        imageUrl: 'https://images.philips.com/is/image/philipsconsumer/ef1aa473b1c3462783f4afab00b3be55',
        platform: 'Amazon TR',
        category: 'home',
        originalPrice: 7999.00,
        discountedPrice: 4999.00,
        discountPercent: 38,
        url: 'https://www.amazon.com.tr',
        isHot: true,
        createdAt: DateTime.now(),
      ),

      // ═══════════ BEBEK ═══════════
      Deal(
        id: 'ty_2',
        title: 'Aptamil Devam Sütü 1200g',
        description: 'Aptamil Pronutra 2 Numara. Trendyol süper fırsat!',
        imageUrl: 'https://cdn.dsmcdn.com/ty537/product/media/images/20221011/0/191283127/584371498/1/1_org_zoom.jpg',
        platform: 'Trendyol',
        category: 'baby',
        originalPrice: 649.90,
        discountedPrice: 449.90,
        discountPercent: 31,
        couponCode: 'MAMA50',
        url: 'https://www.trendyol.com',
        expiryDate: DateTime.now().add(const Duration(days: 2)),
        isFlashDeal: true,
        isHot: true,
        createdAt: DateTime.now(),
      ),

      // ═══════════ GİYİM ═══════════
      Deal(
        id: 'ty_3',
        title: 'Nike Air Max 270',
        description: 'Erkek koşu ayakkabısı. Sezon sonu indirimi!',
        imageUrl: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a28a5da0-2854-4c0a-8035-e30e2c6d7d68/air-max-270-shoes-2V5C4p.png',
        platform: 'Trendyol',
        category: 'fashion',
        originalPrice: 4499.00,
        discountedPrice: 2699.00,
        discountPercent: 40,
        couponCode: 'SPOR500',
        url: 'https://www.trendyol.com',
        expiryDate: DateTime.now().add(const Duration(days: 3)),
        createdAt: DateTime.now(),
      ),

      // ═══════════ MARKET ═══════════
      Deal(
        id: 'mig_1',
        title: 'Ariel Sıvı Deterjan 4x1.3L',
        description: 'Migros\'da dev indirim! 4\'lü paket fırsatı.',
        imageUrl: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/30024600/30024600-a9a4a6-1650x1650.jpg',
        platform: 'Migros',
        category: 'market',
        originalPrice: 529.90,
        discountedPrice: 349.90,
        discountPercent: 34,
        url: 'https://www.migros.com.tr',
        createdAt: DateTime.now(),
      ),
      Deal(
        id: 'getir_2',
        title: 'Getir Market - Haftalık Alışveriş',
        description: 'İlk siparişe özel %20 indirim!',
        imageUrl: 'https://cdn.getir.com/marketing/Getir_water_1620x1080_l2zyg1.jpg',
        platform: 'Getir',
        category: 'market',
        originalPrice: 500.00,
        discountedPrice: 400.00,
        discountPercent: 20,
        couponCode: 'MERHABA20',
        url: 'https://getir.com',
        expiryDate: DateTime.now().add(const Duration(days: 7)),
        createdAt: DateTime.now(),
      ),

      // ═══════════ KOZMETİK ═══════════
      Deal(
        id: 'hb_1',
        title: 'L\'Oreal Paris Revitalift Set',
        description: 'Anti-aging bakım seti. Hepsiburada özel fiyat!',
        imageUrl: 'https://productimages.hepsiburada.net/s/37/375-375/10642670854194.jpg',
        platform: 'Hepsiburada',
        category: 'beauty',
        originalPrice: 999.90,
        discountedPrice: 599.90,
        discountPercent: 40,
        url: 'https://www.hepsiburada.com',
        isHot: true,
        createdAt: DateTime.now(),
      ),
    ];
  }

  static List<Coupon> getCoupons() {
    return [
      // ═══════════ YEMEK KUPONLARI ═══════════
      Coupon(
        id: 'c_ys1',
        code: 'BURGER30',
        platform: 'Yemeksepeti',
        description: 'Burger King siparişlerinde %30 indirim',
        discountPercent: 30,
        minOrderAmount: 150,
        category: 'food',
        expiryDate: DateTime.now().add(const Duration(hours: 12)),
        isVerified: true,
        usageCount: 3420,
        successRate: 89,
        isHidden: true,
      ),
      Coupon(
        id: 'c_ys2',
        code: 'PIZZA40',
        platform: 'Yemeksepeti',
        description: 'Dominos pizza siparişlerinde %40 indirim',
        discountPercent: 40,
        minOrderAmount: 200,
        category: 'food',
        expiryDate: DateTime.now().add(const Duration(days: 1)),
        isVerified: true,
        usageCount: 5600,
        successRate: 88,
        isHidden: true,
      ),
      Coupon(
        id: 'c_ys3',
        code: 'YEMEK100',
        platform: 'Yemeksepeti',
        description: '300₺ üzeri siparişte 100₺ indirim',
        discountAmount: 100,
        minOrderAmount: 300,
        category: 'food',
        expiryDate: DateTime.now().add(const Duration(days: 3)),
        isVerified: true,
        usageCount: 2100,
        successRate: 82,
      ),
      Coupon(
        id: 'c_getir1',
        code: 'MERHABA25',
        platform: 'Getir',
        description: 'İlk siparişe özel %25 indirim',
        discountPercent: 25,
        category: 'food',
        expiryDate: DateTime.now().add(const Duration(days: 7)),
        isVerified: true,
        usageCount: 8900,
        successRate: 97,
      ),
      Coupon(
        id: 'c_getir2',
        code: 'GETIR30TL',
        platform: 'Getir',
        description: 'Getir market 30₺ indirim kodu',
        discountAmount: 30,
        minOrderAmount: 150,
        category: 'market',
        expiryDate: DateTime.now().add(const Duration(days: 3)),
        isVerified: true,
        usageCount: 7800,
        successRate: 96,
        isHidden: true,
      ),

      // ═══════════ E-TİCARET KUPONLARI ═══════════
      Coupon(
        id: 'c_ty1',
        code: 'MAMA50',
        platform: 'Trendyol',
        description: 'Bebek ürünlerinde 50₺ indirim',
        discountAmount: 50,
        minOrderAmount: 200,
        category: 'baby',
        expiryDate: DateTime.now().add(const Duration(days: 2)),
        isVerified: true,
        usageCount: 1245,
        successRate: 94,
        isHidden: true,
      ),
      Coupon(
        id: 'c_ty2',
        code: 'SPOR500',
        platform: 'Trendyol',
        description: 'Spor ürünlerinde 500₺ indirim',
        discountAmount: 500,
        minOrderAmount: 1500,
        category: 'fashion',
        expiryDate: DateTime.now().add(const Duration(days: 3)),
        isVerified: true,
        usageCount: 672,
        successRate: 91,
        isHidden: true,
      ),
      Coupon(
        id: 'c_ty3',
        code: 'KOZMETIK100',
        platform: 'Trendyol',
        description: 'Kozmetik ürünlerinde 100₺ indirim',
        discountAmount: 100,
        minOrderAmount: 300,
        category: 'beauty',
        expiryDate: DateTime.now().add(const Duration(days: 5)),
        isVerified: true,
        usageCount: 450,
        successRate: 92,
        isHidden: true,
      ),
      Coupon(
        id: 'c_hb1',
        code: 'TEKNOFEST',
        platform: 'Hepsiburada',
        description: 'Elektronik ürünlerde %15 indirim',
        discountPercent: 15,
        minOrderAmount: 500,
        category: 'electronics',
        expiryDate: DateTime.now().add(const Duration(days: 10)),
        isVerified: true,
        usageCount: 2100,
        successRate: 85,
      ),
      Coupon(
        id: 'c_amz1',
        code: 'EVIM200',
        platform: 'Amazon TR',
        description: 'Ev & Yaşam kategorisinde 200₺ indirim',
        discountAmount: 200,
        minOrderAmount: 800,
        category: 'home',
        expiryDate: DateTime.now().add(const Duration(days: 4)),
        isVerified: false,
        usageCount: 120,
        successRate: 78,
      ),
      Coupon(
        id: 'c_mig1',
        code: 'MIGROS75',
        platform: 'Migros',
        description: '250₺ üzeri alışverişte 75₺ indirim',
        discountAmount: 75,
        minOrderAmount: 250,
        category: 'market',
        expiryDate: DateTime.now().add(const Duration(days: 6)),
        isVerified: true,
        usageCount: 3200,
        successRate: 93,
      ),
    ];
  }

  static List<PriceHistory> getPriceHistory() {
    final now = DateTime.now();
    return [
      PriceHistory(date: now.subtract(const Duration(days: 30)), price: 649.90, platform: 'Trendyol'),
      PriceHistory(date: now.subtract(const Duration(days: 25)), price: 629.90, platform: 'Trendyol'),
      PriceHistory(date: now.subtract(const Duration(days: 20)), price: 599.90, platform: 'Trendyol'),
      PriceHistory(date: now.subtract(const Duration(days: 15)), price: 549.90, platform: 'Trendyol'),
      PriceHistory(date: now.subtract(const Duration(days: 10)), price: 499.90, platform: 'Trendyol'),
      PriceHistory(date: now.subtract(const Duration(days: 5)), price: 469.90, platform: 'Trendyol'),
      PriceHistory(date: now, price: 449.90, platform: 'Trendyol'),
    ];
  }
}
